### ISSUE TITLE
Add datetime module notebook under dates and time

### ISSUE THREAD

**Issue by Byte7** [Byte7/pypackages#2]
Some suggested modules are - 
1. datetime
2. time
3. calendar

**Comment by Byte7** [comment]
Sure go on!

**Comment by supriyanta** [comment]
Where to add this imports?

**Comment by Byte7** [comment]
I have created the directory structure for the repository, please check it out. Also, the dummy notebooks are created. Fork, branch out, add your code to these notebook (even one will do!) and create a PR. Separate notebooks are made, so that the user can have clear understanding.
Thanks for contributing, keep them coming!
